### ISSUE TITLE
Make it possible to always get the same background color

### ISSUE THREAD

**Issue by Pitmairen** [disintegration/letteravatar#1]
Would it possible to add support for somehow seeding the background color selection with some kind of key so that when the same key is used it always results in the  the same background color?

This would be useful if one for example want to generate avatars for users and use the username as a key so that the same user always have the same background color.

**Comment by disintegration** [comment]
Hi!

Do you mean an another function taking a string key instead of a rune?

I can see how I can incorporate an additional option so the same letter will always have the same color. But it's probably not what you want.

**Comment by Pitmairen** [comment]
I'm not sure whats is the best way to implement it, but it would be nice if it was possible to do something like this:

If there are multiple users with similar names:
Andy
Andy2
Andy3

They all get the same letter "A" in the avatar, but each one get a different color because the names are not identical. But each of them always get the same color every time the avatar is generated. 

Currently the background color is picked randomly so each time the avatar is generated a different color is picked.  It would be nice if it was possible to pass in an extra parameter that would act as a seed that was used to pick a random color.  

``` go
// These functions should return different background colors because
// the seed is different, but the same seed should always generate the same color
Draw(100, 'A', &letteravatar.Options{
    Seed: "Andy"
})
Draw(100, 'A', &letteravatar.Options{
    Seed: "Andy2"
})


```

**Comment by disintegration** [comment]
Thank you for the clarification! It would be useful indeed.
Will look into it.

**Comment by disintegration** [comment]
Implemented in https://github.com/disintegration/letteravatar/commit/2d2b9a0791e5149dff2c02007726bfecb1dab7cb.

**Comment by Pitmairen** [comment]
Thank you! Exactly what i needed.
